name: Custom commit
on: 
  workflow_dispatch:
    inputs:
      name:
        type: string
        description: custom name

jobs:
  get-users-list:
    runs-on: ubuntu-latest
    steps:
          
      - name: Checkout ...
        uses: actions/checkout@v3
      - run: |
          echo 'Check before'
          git diff commit-test.txt
          git config user.name mariiapaniutina
          git config user.email mariia.paniutina@gmail.com
          echo 'test' >> commit-test.txt
          echo 'Check after'
          git diff commit-test.txt
          git commit -m 'Overwritten with Github Actions by {inputs.name}'
          git push
