name: Users generation

on: 
  # NOTE :: we can add pull request closed, etc
  workflow_dispatch:
  
jobs:
  get-users-list:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3
      - name: committing in workflow
        env:
            GITHUB_TOKEN: ${{ secrets.GHA-TEST }}
        run: |
            echo ${{ secrets }}
            sed -i -e "s/\$USER_OPTIONS/- one/" .github/workflows/user-deployment.yml
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m 'Overwritten by Github Actions'
            git push
