name: Users generation

on: 
  # NOTE :: we can add pull request closed, etc
  workflow_dispatch:
  
jobs:
  get-users-list:
    runs-on: ubuntu-latest
    steps:
          
      - name: Checkout ...
        uses: actions/checkout@v3
        with:
          # repository: mariiapaniutina/gha-test
          token: ${{ secrets.GHA_1 }}
          # token: ${{ github.token }}
          # path: .github/workflows
      
      - run: |
          echo "File before change"
          cat .github/workflows/user-deployment.yml
          # sed -i "s/\$USER_OPTIONS/- user1/" .github/workflows/user-deployment.yml
          RANDOM_USER=$((1 + $RANDOM % 10))
          REPLACE_STR='      name:        type: choice        description: List of usernames        options:          -user'
          sed -i "s/\s*name:\s*type: choice\s*description: List of usernames\s*options:\s*[-{1}\s\[a-zA-Z0-9]*]?$/${REPLACE_STR}${RANDOM_USER}"
          echo "File after change"
          cat .github/workflows/user-deployment.yml
          git config user.name mariiapaniutina
          git config user.email mariia.paniutina@gmail.com
          git status
          ls -la .github/workflows
          git add -A
          git commit -m 'Overwritten by Github Actions'
          git push
