name: User deployment
on: 
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: List of usernames
        options: 
          $USER_OPTIONS

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Getting overall data
        run: |
          echo "User name: test" >> $GITHUB_STEP_SUMMARY
          echo "Age: 34" >> $GITHUB_STEP_SUMMARY
          echo "Type: Admin" >> $GITHUB_STEP_SUMMARY
          echo "Control level: Boss" >> $GITHUB_STEP_SUMMARY
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Get the user name
        run:  |
          echo ${{ inputs.name }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo ${{ inputs.name }} can test,
