name: Users generation

on: 
  # NOTE :: we can add pull request closed, etc
  workflow_dispatch:
  
jobs:
  get-users-list:
    runs-on: ubuntu-latest
    steps:

      - name: Get All users from simple API
        run: |
          output="- userone\n          "
          output+="- usertwo\n          "
          output+="- userthree\n          "
          echo "current `pwd`"
          echo "list `ls -la`"
          echo $output
          # sed "s/\$USER_OPTIONS/$output/" user-deployment.yml
          sed "s/$USER_OPTIONS/- one/" gha-test/.github/workflows/user-deployment.yml
