name: Users generation

on: 
  # NOTE :: we can add pull request closed, etc
  workflow_dispatch:
  
jobs:
  get-users-list:
    runs-on: ubuntu-latest
    steps:
          
      - name: Checkout ...
        uses: actions/checkout@v3
        with:
          repository: mariiapaniutina/gha-test
          token: ${{ secrets.GHA_1 }}
          # token: ${{ github.token }}
          path: .github/workflows
      
      - run: |
          sed "s/\$USER_OPTIONS/- two/" .github/workflows/user-deployment.yml > .github/workflows/user-deployment.yml
          git config user.name mariiapaniutina
          git config user.email mariia.paniutina@gmail.com
          git add -A
          git commit -m 'Overwritten by Github Actions'
          git push
