name: User deployment
on: 
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: List of usernames
        options: 
          - two

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Get the user name
        run:  |
          echo ${{ inputs.name }}
          echo "{User name done}" >> $GITHUB_STEP_SUMMARY

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo ${{ inputs.name }} can test,
          echo "{Last one done}" >> $GITHUB_STEP_SUMMARY
