name: Users generation

on: 
  # NOTE :: we can add pull request closed, etc
  workflow_dispatch:
  
jobs:
  get-users-list:
    runs-on: ubuntu-latest
    steps:
      # - name: Get All users from simple API
      #  run: |
      #    output="- userone\n          "
      #    output+="- usertwo\n          "
      #   output+="- userthree\n          "
          # echo "current `pwd`"
          # echo "list `ls -la`"
          # echo $output
          # echo ${{ env.home}}
          # sed "s/\$USER_OPTIONS/$output/" user-deployment.yml
         # sed "s/\$USER_OPTIONS/- one/" .github/workflows/user-deployment.yml
          
      - name: Overwrite file
        uses: "DamianReeves/write-file-action@master"
        with:
          path: .github/workflows/user-deployment.yml
          write-mode: overwrite
          contents: |
            console.log('some contents')
          
      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          message: 'Overwritten by Github Actions - ${date}'
