name: User deployment
on: 
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: List of usernames
        options: 
          - user1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Getting overall data
        run: |
          echo "User name: test" >> $GITHUB_STEP_SUMMARY
          echo "Age: 34" >> $GITHUB_STEP_SUMMARY
          echo "Type: Admin" >> $GITHUB_STEP_SUMMARY
          echo "Control level: Boss" >> $GITHUB_STEP_SUMMARY
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Get the user name
        run:  |
          echo ${{ inputs.name }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo ${{ inputs.name }} can test,
          
  build2:
    runs-on: ubuntu-latest

    steps:
      - name: Getting overall data
        run: |
          echo "User name: test2" >> $GITHUB_STEP_SUMMARY
          echo "Age: 44" >> $GITHUB_STEP_SUMMARY
          echo "Type: Admin" >> $GITHUB_STEP_SUMMARY
          echo "Control level: Boss" >> $GITHUB_STEP_SUMMARY
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Get the user name
        run:  |
          echo ${{ inputs.name }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo ${{ inputs.name }} can test,
          
  overview:
    runs-on: ubuntu-latest

    steps:
      - name: Getting overall data
        run: |
          echo "<table>" >> $GITHUB_STEP_SUMMARY
          echo "<tr>" >> $GITHUB_STEP_SUMMARY
          echo "<th colspan='3' align='left'>Staging</th>" >> $GITHUB_STEP_SUMMARY
          echo "</tr>" >> $GITHUB_STEP_SUMMARY
          echo "<tr>" >> $GITHUB_STEP_SUMMARY
          echo "<td bgcolor='#dcf0cb'>ei-ltx1|alpha</td>" >> $GITHUB_STEP_SUMMARY
          echo "<td bgcolor='#dcf0cb'>0.0.1</td>" >> $GITHUB_STEP_SUMMARY
          echo "<td bgcolor='#dcf0cb'><b>Succeed</b></td>" >> $GITHUB_STEP_SUMMARY
          echo "</tr>" >> $GITHUB_STEP_SUMMARY
          echo "<tr>" >> $GITHUB_STEP_SUMMARY
          echo "<td bgcolor='#ffe0db'>ei-ltx1|beta</td>" >> $GITHUB_STEP_SUMMARY
          echo "<td bgcolor='#ffe0db'>0.0.1</td>" >> $GITHUB_STEP_SUMMARY
          echo "<td bgcolor='#ffe0db'><b>Failed</b></td>" >> $GITHUB_STEP_SUMMARY
          echo "</tr>" >> $GITHUB_STEP_SUMMARY
          echo "</table>" >> $GITHUB_STEP_SUMMARY
